service:
  name: serverless-todo-app

plugins:
  - serverless-webpack
  - serverless-iam-roles-per-function
  - serverless-reqvalidator-plugin
  - serverless-aws-documentation
  - serverless-plugin-canary-deployments
  # - serverless-plugin-tracing  
  - serverless-dynamodb-local  
  - serverless-s3-local
  - serverless-offline

# Uncomment to enable individual packaging
# package:
#   individually: true  

provider:
  name: aws
  runtime: nodejs12.x

  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}

  # tracing:
    # lambda: true
    # apiGateway: true

  environment:
    CART_TABLE: cart-${self:provider.stage}      
    ITEM_TABLE: item-${self:provider.stage}    
    ORDER_TABLE: order-${self:provider.stage}    
    ORDER_UID_GIDX: order-uid-gidx-${self:provider.stage}    
    SEQ_TABLE: seq-${self:provider.stage}                  
    STORE_TABLE: store-${self:provider.stage}  
    USER_TABLE: user-${self:provider.stage}      
    USER_UID_GIDX: user-uid-gidx-${self:provider.stage}
    ITEM_IMG_S3_BUCKET: gmp-ucart-img-${self:provider.stage}
    ITEM_IMG_S_S3_BUCKET: gmp-ucart-img-s-${self:provider.stage}    
    SIGNED_URL_EXPIRATION: 300
  #   AUTH_0_SECRET_ID: Auth0Secret-${self:provider.stage}
  #   AUTH_0_SECRET_FIELD: auth0Secret

  iamRoleStatements:
    - Effect: Allow
      Action:
        - codedeploy:*
      Resource:
        - '*'
    - Effect: Allow
      Action:
        - dynamodb:Scan
        - dynamodb:PutItem
        - dynamodb:GetItem
      Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.TODOS_TABLE}
    - Effect: Allow
      Action:
        - dynamodb:Query
      Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.TODOS_TABLE}/index/${self:provider.environment.TODOS_USR_INDEX}
    - Effect: "Allow" 
      Action:
        - "xray:PutTraceSegments"
        - "xray:PutTelemetryRecords"
      Resource:
        - "*"
custom:
  serverless-offline:
    port: 3003
#    useChildProcesses: true    
  dynamodb:
    # noStart: true
    start:
      port: 8000
      inMemory: true
      migrate: true
    seed:
      seqTable:
        sources:
          - table: ${self:provider.environment.SEQ_TABLE}
            sources: [./tst/seed-seq.json]
    stages:
      - test 
      - dev        
  s3:
    host: localhost
    directory: /tmp

  itemImageS3TopicName: item-image-topic-${self:provider.stage}    

  documentation:
    api:
      info:
        version: v1.0.0
        title: Todo API
        description: Serverless application for Todo API
    models:
      - name: CartReq
        contentType: application/json
        schema: ${file(models/create-cart-req.json)}
      - name: ItemReq
        contentType: application/json
        schema: ${file(models/create-item-req.json)}
      - name: OrderReq
        contentType: application/json
        schema: ${file(models/create-order-req.json)}
      - name: StoreReq
        contentType: application/json
        schema: ${file(models/create-store-req.json)}
      - name: UserReq
        contentType: application/json
        schema: ${file(models/create-user-req.json)}

functions:
  Auth:
    handler: src/lambda/auth/auth0Authorizer.handler

  GetTodos:
    handler: src/lambda/http/getTodos.handler
    events:
      - http:
          method: get
          path: todos
          cors: true  
          authorizer: Auth          
    iamRoleStatementsInherit: true                      
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:Query
        Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.TODOS_TABLE}
      - Effect: Allow
        Action:
          - dynamodb:Query
        Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.TODOS_TABLE}/index/${self:provider.environment.TODOS_USR_INDEX}
      - Effect: Allow
        Action:
          - s3:GetObject
        Resource: arn:aws:s3:::${self:provider.environment.ITEM_IMG_S3_BUCKET}/*
      - Effect: Allow
        Action:
          - xray:PutTraceSegments
          - xray:PutTelemetryRecords
        Resource: "*"  

  CreateTodo:
    handler: src/lambda/http/createTodo.handler
    events:
      - http:
          method: post
          path: todos
          cors: true          
          authorizer: Auth                    
          request:
            # Schema that will validate the incoming requests
            schema:
              application/json: ${file(models/create-todo-req.json)}

  UpdateTodo:
    handler: src/lambda/http/updateTodo.handler
    events:
      - http:
          method: patch
          path: todos/{todoId}
          cors: true 
          authorizer: Auth                                                 
          request:
            # Schema that will validate the incoming requests
            schema:
              application/json: ${file(models/update-todo-req.json)}
    iamRoleStatementsInherit: true
    iamRoleStatementsName: updateTodoRole
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:UpdateItem
        Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.TODOS_TABLE}

  DeleteTodo:
    handler: src/lambda/http/deleteTodo.handler
    events:
      - http:
          method: delete
          path: todos/{todoId}
          cors: true                    
          authorizer: Auth                    
    iamRoleStatementsInherit: true
    iamRoleStatementsName: deleteTodoRole
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:DeleteItem
        Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.TODOS_TABLE}

  GenerateUploadUrl:
    handler: src/lambda/http/generateUploadUrl.handler
    events:
      - http:
          method: post
          path: todos/{todoId}/attachment
          cors: true                    
          authorizer: Auth     
    iamRoleStatementsInherit: true
    iamRoleStatementsName: generateUrlTodoRole
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:UpdateItem
        Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.TODOS_TABLE}  
      - Effect: Allow
        Action:
          - s3:PutObject
        Resource: arn:aws:s3:::${self:provider.environment.ITEM_IMG_S3_BUCKET}/*

  # ResizeImage:
  #   handler: src/lambda/s3/resizeImage.handler
  #   events:
  #     - sns:
  #         arn:
  #           Fn::Join:
  #             - ':'
  #             - - arn:aws:sns
  #               - Ref: AWS::Region
  #               - Ref: AWS::AccountId
  #               - ${self:custom.itemImageS3TopicName}
  #         topicName: ${self:custom.itemImageS3TopicName}

resources:
  Resources:   
    GatewayResponseDefault4XX:
      Type: AWS::ApiGateway::GatewayResponse
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
          gatewayresponse.header.Access-Control-Allow-Methods: "'GET,OPTIONS,POST'"
        ResponseType: DEFAULT_4XX
        RestApiId:
          Ref: ApiGatewayRestApi

    RequestBodyValidator:
      Type: AWS::ApiGateway::RequestValidator
      Properties:
        Name: 'request-body-validator'
        RestApiId:
          Ref: ApiGatewayRestApi
        ValidateRequestBody: true
        ValidateRequestParameters: false          

    CartTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.CART_TABLE}        
        AttributeDefinitions:
          - AttributeName: userNum
            AttributeType: N
          - AttributeName: storeNum
            AttributeType: N
          - AttributeName: createdAt
            AttributeType: S
        KeySchema:
          - AttributeName: userNum
            KeyType: HASH
          - AttributeName: storeNum
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
    
    ItemTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.ITEM_TABLE}        
        AttributeDefinitions:
          - AttributeName: itemId
            AttributeType: S
          - AttributeName: storeNum
            AttributeType: N
          - AttributeName: itemNum
            AttributeType: N            
          - AttributeName: name
            AttributeType: S
          - AttributeName: desc
            AttributeType: S
        KeySchema:
          - AttributeName: itemId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

    OrderTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.ORDER_TABLE}        
        AttributeDefinitions:
          - AttributeName: orderId
            AttributeType: S
          - AttributeName: storeNum
            AttributeType: N
          - AttributeName: orderNum
            AttributeType: N            
          - AttributeName: userNum
            AttributeType: N
          - AttributeName: createdAt
            AttributeType: S
        KeySchema:
          - AttributeName: orderId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        GlobalSecondaryIndexes:
          - IndexName: ${self:provider.environment.ORDER_UID_GIDX}
            KeySchema:
              - AttributeName: userId
                KeyType: HASH
              - AttributeName: createdAt
                KeyType: RANGE
            Projection:
              ProjectionType: INCLUDE 
              NonKeyAttributes:
                - orderId
    StoreTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.STORE_TABLE}        
        AttributeDefinitions:
          - AttributeName: storeNum
            AttributeType: N
          - AttributeName: name
            AttributeType: S
          - AttributeName: desc
            AttributeType: S
          - AttributeName: createdAt
            AttributeType: S
        KeySchema:
          - AttributeName: storeNum
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

    UserTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.USER_TABLE}        
        AttributeDefinitions:
          - AttributeName: userNum
            AttributeType: N
          - AttributeName: userId
            AttributeType: S
          - AttributeName: name
            AttributeType: S         
          - AttributeName: createdAt
            AttributeType: S
        KeySchema:
          - AttributeName: userNum
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        GlobalSecondaryIndexes:
          - IndexName: ${self:provider.environment.USER_UID_GIDX}
            KeySchema:
              - AttributeName: userId
                KeyType: HASH
            Projection:
              ProjectionType: ALL # What attributes will be copied to an index
          
    ItemImageBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:provider.environment.ITEM_IMG_S3_BUCKET}
        # NotificationConfiguration:
        #   TopicConfigurations:
        #     - Event: s3:ObjectCreated:Put
        #       Topic: !Ref ItemImagesTopic        
        CorsConfiguration:
          CorsRules:
            -
              AllowedOrigins:
                - '*'
              AllowedHeaders:
                - '*'
              AllowedMethods:
                - GET
                - PUT
                - POST
                - DELETE
                - HEAD
              MaxAge: 3000    

    # ItemImagesTopic:
    #   Type: AWS::SNS::Topic
    #   Properties:
    #     DisplayName: Item Image bucket topic
    #     TopicName: ${self:custom.itemImageS3TopicName}

    BucketPolicy1:
      Type: AWS::S3::BucketPolicy
      Properties:
        PolicyDocument:
          Id: MyPolicy
          Version: "2012-10-17"
          Statement:
            - Sid: PublicReadForGetBucketObjects
              Effect: Allow
              Principal: '*'
              Action: 's3:GetObject'
              Resource: 'arn:aws:s3:::${self:provider.environment.ITEM_IMG_S3_BUCKET}/*'
        Bucket: !Ref ItemImageBucket 


    # SNSTopicPolicy:
    #   Type: AWS::SNS::TopicPolicy
    #   Properties:
    #     PolicyDocument:
    #       Version: "2012-10-17"
    #       Statement:
    #         - Effect: Allow
    #           Principal:
    #             AWS: "*"
    #           Action: sns:Publish
    #           Resource:
    #             !Ref ItemImagesTopic
    #           Condition:
    #             ArnLike:
    #               AWS:SourceArn: arn:aws:s3:::${self:provider.environment.ITEM_IMG_S3_BUCKET}
    #     Topics:
    #       - !Ref ItemImagesTopic

    ItemImageThumbNailBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:provider.environment.ITEM_IMG_S_S3_BUCKET}
        CorsConfiguration:
          CorsRules:
            -
              AllowedOrigins:
                - '*'
              AllowedHeaders:
                - '*'
              AllowedMethods:
                - GET
                - PUT
                - POST
                - DELETE
                - HEAD
              MaxAge: 3000    

    BucketPolicy2:
      Type: AWS::S3::BucketPolicy
      Properties:
        PolicyDocument:
          Id: MyPolicy
          Version: "2012-10-17"
          Statement:
            - Sid: PublicReadForGetBucketObjects
              Effect: Allow
              Principal: '*'
              Action: 's3:GetObject'
              Resource: 'arn:aws:s3:::${self:provider.environment.ITEM_IMG_S_S3_BUCKET}/*'
        Bucket: !Ref ItemImageThumbNailBucket      

